# Generated by Django 2.2 on 2020-07-07 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='end_time',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='start_time',
            new_name='start_datetime',
        ),
    ]
